name = "GENeSYSMOD"
uuid = "9f3a37f9-d498-4265-a124-3ae3e9ff3acf"
authors = ["Dimitri Pinel <dimitri.pinel@sintef.no>", "Lars Hellemo <lars.hellemo@sintef.no>"]
version = "4.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"

[compat]
CSV = "^0.10.11"
DataFrames = "^1.3.4"
JuMP = "^1.11"
XLSX = "^0.10.4"
julia = "^1.8.5"
HiGHS = "^1.19"
Ipopt = "^1.11"
DocumenterTools = "^0.1"
PyCall = "^1.96.4"
Conda = "^1.10.2"
LibGit2 = "^1.10.0"